#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEE926C2BDACC177B (fabiano@fidencio.org)
#
Name     : osinfo-db-tools
Version  : 1.3.0
Release  : 4
URL      : https://releases.pagure.org/libosinfo/osinfo-db-tools-1.3.0.tar.gz
Source0  : https://releases.pagure.org/libosinfo/osinfo-db-tools-1.3.0.tar.gz
Source1  : https://releases.pagure.org/libosinfo/osinfo-db-20180416.tar.xz
Source99 : https://releases.pagure.org/libosinfo/osinfo-db-tools-1.3.0.tar.gz.asc
Summary  : Tools for managing the osinfo database
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: osinfo-db-tools-bin = %{version}-%{release}
Requires: osinfo-db-tools-data = %{version}-%{release}
Requires: osinfo-db-tools-license = %{version}-%{release}
Requires: osinfo-db-tools-locales = %{version}-%{release}
Requires: osinfo-db-tools-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(libxslt)

%description
This package provides tools for managing the osinfo database of
information about operating systems for use with virtualization

%package bin
Summary: bin components for the osinfo-db-tools package.
Group: Binaries
Requires: osinfo-db-tools-data = %{version}-%{release}
Requires: osinfo-db-tools-license = %{version}-%{release}
Requires: osinfo-db-tools-man = %{version}-%{release}

%description bin
bin components for the osinfo-db-tools package.


%package data
Summary: data components for the osinfo-db-tools package.
Group: Data

%description data
data components for the osinfo-db-tools package.


%package license
Summary: license components for the osinfo-db-tools package.
Group: Default

%description license
license components for the osinfo-db-tools package.


%package locales
Summary: locales components for the osinfo-db-tools package.
Group: Default

%description locales
locales components for the osinfo-db-tools package.


%package man
Summary: man components for the osinfo-db-tools package.
Group: Default

%description man
man components for the osinfo-db-tools package.


%prep
%setup -q -n osinfo-db-tools-1.3.0
cd ..
%setup -q -T -D -n osinfo-db-tools-1.3.0 -b 1
mkdir -p osinfo-db
cp -r %{_topdir}/BUILD/osinfo-db-20180416/* %{_topdir}/BUILD/osinfo-db-tools-1.3.0/osinfo-db

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549123255
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1549123255
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/osinfo-db-tools
cp COPYING %{buildroot}/usr/share/package-licenses/osinfo-db-tools/COPYING
cp osinfo-db/LICENSE %{buildroot}/usr/share/package-licenses/osinfo-db-tools/osinfo-db_LICENSE
%make_install
%find_lang osinfo-db-tools
## install_append content
mkdir -p %{buildroot}/usr/share/osinfo
tar --strip-components=1 -xJf %{SOURCE1} -C %{buildroot}/usr/share/osinfo
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/osinfo-db-export
/usr/bin/osinfo-db-import
/usr/bin/osinfo-db-path
/usr/bin/osinfo-db-validate

%files data
%defattr(-,root,root,-)
/usr/share/osinfo/LICENSE
/usr/share/osinfo/VERSION
/usr/share/osinfo/datamap/microsoft.com/win-7-l10n-language.xml
/usr/share/osinfo/datamap/microsoft.com/win-8-l10n-language-reverse.xml
/usr/share/osinfo/datamap/microsoft.com/win-8-l10n-language.xml
/usr/share/osinfo/datamap/x.org/x11-keyboard.xml
/usr/share/osinfo/device/ibasetechnologies.net/isa-ib700.xml
/usr/share/osinfo/device/ibm.com/ps2-keyboard.xml
/usr/share/osinfo/device/ibm.com/ps2-mouse.xml
/usr/share/osinfo/device/pcisig.com/pci-1000-0012.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1013-00b8.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1022-2000.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-10ec-8029.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-10ec-8139.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1234-1111.xml
/usr/share/osinfo/device/pcisig.com/pci-1274-5000.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-15ad-0710.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1000.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1001.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1002.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1003.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1004.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1005.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1009.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1041.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1042.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1043.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1044.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1045.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1048.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1049.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1050.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1af4-1052.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-1b36-0100.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-8086-100e.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-8086-2415.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-8086-25ab.d/class.xml
/usr/share/osinfo/device/pcisig.com/pci-8086-2668.d/class.xml
/usr/share/osinfo/device/usb.org/usb-80ee-0021.d/class.xml
/usr/share/osinfo/device/xen.org/xen-console.xml
/usr/share/osinfo/device/xen.org/xen-pci.xml
/usr/share/osinfo/device/xen.org/xen-vbd.xml
/usr/share/osinfo/device/xen.org/xen-vfb.xml
/usr/share/osinfo/device/xen.org/xen-vif.xml
/usr/share/osinfo/device/xen.org/xen-vkbd.xml
/usr/share/osinfo/device/xen.org/xen-vscsi.xml
/usr/share/osinfo/device/xen.org/xen-vtpm.xml
/usr/share/osinfo/install-script/debian.org/debian-preseed-desktop.xml
/usr/share/osinfo/install-script/debian.org/debian-preseed-jeos.xml
/usr/share/osinfo/install-script/fedoraproject.org/fedora-kickstart-desktop.xml
/usr/share/osinfo/install-script/fedoraproject.org/fedora-kickstart-jeos.xml
/usr/share/osinfo/install-script/microsoft.com/windows-cmd-desktop.xml
/usr/share/osinfo/install-script/microsoft.com/windows-reg-desktop.xml
/usr/share/osinfo/install-script/microsoft.com/windows-sif-desktop.xml
/usr/share/osinfo/install-script/microsoft.com/windows-sif-jeos.xml
/usr/share/osinfo/install-script/microsoft.com/windows-unattend-desktop.xml
/usr/share/osinfo/install-script/microsoft.com/windows-unattend-jeos.xml
/usr/share/osinfo/install-script/opensuse.org/opensuse-autoyast-desktop.xml
/usr/share/osinfo/install-script/opensuse.org/opensuse-autoyast-jeos.xml
/usr/share/osinfo/install-script/redhat.com/rhel-kickstart-desktop.xml
/usr/share/osinfo/install-script/redhat.com/rhel-kickstart-jeos.xml
/usr/share/osinfo/install-script/ubuntu.com/ubuntu-preseed-jeos.xml
/usr/share/osinfo/os/alpinelinux.org/alpinelinux-3.5.xml
/usr/share/osinfo/os/alpinelinux.org/alpinelinux-3.6.xml
/usr/share/osinfo/os/alpinelinux.org/alpinelinux-3.7.xml
/usr/share/osinfo/os/altlinux.org/altlinux-1.0.xml
/usr/share/osinfo/os/altlinux.org/altlinux-2.0.xml
/usr/share/osinfo/os/altlinux.org/altlinux-2.2.xml
/usr/share/osinfo/os/altlinux.org/altlinux-2.4.xml
/usr/share/osinfo/os/altlinux.org/altlinux-3.0.xml
/usr/share/osinfo/os/altlinux.org/altlinux-4.0.xml
/usr/share/osinfo/os/altlinux.org/altlinux-4.1.xml
/usr/share/osinfo/os/altlinux.org/altlinux-5.0.xml
/usr/share/osinfo/os/altlinux.org/altlinux-6.0.xml
/usr/share/osinfo/os/altlinux.org/altlinux-7.0.xml
/usr/share/osinfo/os/apple.com/macosx-10.0.xml
/usr/share/osinfo/os/apple.com/macosx-10.1.xml
/usr/share/osinfo/os/apple.com/macosx-10.2.xml
/usr/share/osinfo/os/apple.com/macosx-10.3.xml
/usr/share/osinfo/os/apple.com/macosx-10.4.xml
/usr/share/osinfo/os/apple.com/macosx-10.5.xml
/usr/share/osinfo/os/apple.com/macosx-10.6.xml
/usr/share/osinfo/os/apple.com/macosx-10.7.xml
/usr/share/osinfo/os/asianux.com/asianux-4.6.xml
/usr/share/osinfo/os/asianux.com/asianux-4.7.xml
/usr/share/osinfo/os/asianux.com/asianux-7.0.xml
/usr/share/osinfo/os/asianux.com/asianux-7.1.xml
/usr/share/osinfo/os/asianux.com/asianux-7.2.xml
/usr/share/osinfo/os/asianux.com/asianux-unknown.xml
/usr/share/osinfo/os/centos.org/centos-6.0.xml
/usr/share/osinfo/os/centos.org/centos-6.1.xml
/usr/share/osinfo/os/centos.org/centos-6.2.xml
/usr/share/osinfo/os/centos.org/centos-6.3.xml
/usr/share/osinfo/os/centos.org/centos-6.4.xml
/usr/share/osinfo/os/centos.org/centos-6.5.xml
/usr/share/osinfo/os/centos.org/centos-6.6.xml
/usr/share/osinfo/os/centos.org/centos-6.7.xml
/usr/share/osinfo/os/centos.org/centos-6.8.xml
/usr/share/osinfo/os/centos.org/centos-6.9.xml
/usr/share/osinfo/os/centos.org/centos-7.0.xml
/usr/share/osinfo/os/debian.org/debian-1.1.xml
/usr/share/osinfo/os/debian.org/debian-1.2.xml
/usr/share/osinfo/os/debian.org/debian-1.3.xml
/usr/share/osinfo/os/debian.org/debian-2.0.xml
/usr/share/osinfo/os/debian.org/debian-2.1.xml
/usr/share/osinfo/os/debian.org/debian-2.2.xml
/usr/share/osinfo/os/debian.org/debian-3.1.xml
/usr/share/osinfo/os/debian.org/debian-3.xml
/usr/share/osinfo/os/debian.org/debian-4.xml
/usr/share/osinfo/os/debian.org/debian-5.xml
/usr/share/osinfo/os/debian.org/debian-6.xml
/usr/share/osinfo/os/debian.org/debian-7.xml
/usr/share/osinfo/os/debian.org/debian-8.xml
/usr/share/osinfo/os/debian.org/debian-9.xml
/usr/share/osinfo/os/debian.org/debian-testing.xml
/usr/share/osinfo/os/endlessos.com/eos-3.3.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-1.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-10.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-11.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-12.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-13.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-14.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-15.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-16.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-17.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-18.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-19.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-2.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-20.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-21.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-22.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-23.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-24.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-25.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-26.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-27.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-3.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-4.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-5.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-6.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-7.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-8.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-9.xml
/usr/share/osinfo/os/fedoraproject.org/fedora-unknown.xml
/usr/share/osinfo/os/freebsd.org/freebsd-1.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-10.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-10.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-10.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-10.3.xml
/usr/share/osinfo/os/freebsd.org/freebsd-10.4.xml
/usr/share/osinfo/os/freebsd.org/freebsd-11.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-11.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-2.0.5.xml
/usr/share/osinfo/os/freebsd.org/freebsd-2.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-2.2.8.xml
/usr/share/osinfo/os/freebsd.org/freebsd-2.2.9.xml
/usr/share/osinfo/os/freebsd.org/freebsd-3.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-3.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.10.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.11.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.3.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.4.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.5.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.6.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.7.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.8.xml
/usr/share/osinfo/os/freebsd.org/freebsd-4.9.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.2.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.3.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.4.xml
/usr/share/osinfo/os/freebsd.org/freebsd-5.5.xml
/usr/share/osinfo/os/freebsd.org/freebsd-6.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-6.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-6.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-6.3.xml
/usr/share/osinfo/os/freebsd.org/freebsd-6.4.xml
/usr/share/osinfo/os/freebsd.org/freebsd-7.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-7.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-7.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-7.3.xml
/usr/share/osinfo/os/freebsd.org/freebsd-7.4.xml
/usr/share/osinfo/os/freebsd.org/freebsd-8.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-8.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-8.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-8.3.xml
/usr/share/osinfo/os/freebsd.org/freebsd-8.4.xml
/usr/share/osinfo/os/freebsd.org/freebsd-9.0.xml
/usr/share/osinfo/os/freebsd.org/freebsd-9.1.xml
/usr/share/osinfo/os/freebsd.org/freebsd-9.2.xml
/usr/share/osinfo/os/freebsd.org/freebsd-9.3.xml
/usr/share/osinfo/os/freedos.org/freedos-1.2.xml
/usr/share/osinfo/os/gnome.org/gnome-3.6.xml
/usr/share/osinfo/os/gnome.org/gnome-3.8.xml
/usr/share/osinfo/os/gnome.org/gnome-continuous-3.10.xml
/usr/share/osinfo/os/gnome.org/gnome-continuous-3.12.xml
/usr/share/osinfo/os/gnome.org/gnome-continuous-3.14.xml
/usr/share/osinfo/os/mageia.org/mageia-1.xml
/usr/share/osinfo/os/mageia.org/mageia-2.xml
/usr/share/osinfo/os/mageia.org/mageia-3.xml
/usr/share/osinfo/os/mageia.org/mageia-4.xml
/usr/share/osinfo/os/mageia.org/mageia-5.xml
/usr/share/osinfo/os/mageia.org/mageia-6.xml
/usr/share/osinfo/os/mandriva.com/mandrake-10.0.xml
/usr/share/osinfo/os/mandriva.com/mandrake-10.1.xml
/usr/share/osinfo/os/mandriva.com/mandrake-10.2.xml
/usr/share/osinfo/os/mandriva.com/mandrake-5.1.xml
/usr/share/osinfo/os/mandriva.com/mandrake-5.2.xml
/usr/share/osinfo/os/mandriva.com/mandrake-5.3.xml
/usr/share/osinfo/os/mandriva.com/mandrake-6.0.xml
/usr/share/osinfo/os/mandriva.com/mandrake-6.1.xml
/usr/share/osinfo/os/mandriva.com/mandrake-7.0.xml
/usr/share/osinfo/os/mandriva.com/mandrake-7.1.xml
/usr/share/osinfo/os/mandriva.com/mandrake-7.2.xml
/usr/share/osinfo/os/mandriva.com/mandrake-8.0.xml
/usr/share/osinfo/os/mandriva.com/mandrake-8.1.xml
/usr/share/osinfo/os/mandriva.com/mandrake-8.2.xml
/usr/share/osinfo/os/mandriva.com/mandrake-9.0.xml
/usr/share/osinfo/os/mandriva.com/mandrake-9.1.xml
/usr/share/osinfo/os/mandriva.com/mandrake-9.2.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2006.0.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2007.1.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2007.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2008.0.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2008.1.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2009.0.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2009.1.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2010.0.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2010.1.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2010.2.xml
/usr/share/osinfo/os/mandriva.com/mandriva-2011.xml
/usr/share/osinfo/os/mandriva.com/mbs-1.0.xml
/usr/share/osinfo/os/mandriva.com/mes-5.0.xml
/usr/share/osinfo/os/mandriva.com/mes-5.1.xml
/usr/share/osinfo/os/microsoft.com/msdos-6.22.xml
/usr/share/osinfo/os/microsoft.com/win-1.0.xml
/usr/share/osinfo/os/microsoft.com/win-10.xml
/usr/share/osinfo/os/microsoft.com/win-2.0.xml
/usr/share/osinfo/os/microsoft.com/win-2.1.xml
/usr/share/osinfo/os/microsoft.com/win-2k.xml
/usr/share/osinfo/os/microsoft.com/win-2k12.xml
/usr/share/osinfo/os/microsoft.com/win-2k12r2.xml
/usr/share/osinfo/os/microsoft.com/win-2k16.xml
/usr/share/osinfo/os/microsoft.com/win-2k3.xml
/usr/share/osinfo/os/microsoft.com/win-2k3r2.xml
/usr/share/osinfo/os/microsoft.com/win-2k8.xml
/usr/share/osinfo/os/microsoft.com/win-2k8r2.xml
/usr/share/osinfo/os/microsoft.com/win-3.1.xml
/usr/share/osinfo/os/microsoft.com/win-7.xml
/usr/share/osinfo/os/microsoft.com/win-8.1.xml
/usr/share/osinfo/os/microsoft.com/win-8.xml
/usr/share/osinfo/os/microsoft.com/win-95.xml
/usr/share/osinfo/os/microsoft.com/win-98.xml
/usr/share/osinfo/os/microsoft.com/win-me.xml
/usr/share/osinfo/os/microsoft.com/win-vista.xml
/usr/share/osinfo/os/microsoft.com/win-xp.xml
/usr/share/osinfo/os/microsoft.com/winnt-3.1.xml
/usr/share/osinfo/os/microsoft.com/winnt-3.5.xml
/usr/share/osinfo/os/microsoft.com/winnt-3.51.xml
/usr/share/osinfo/os/microsoft.com/winnt-4.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-0.8.xml
/usr/share/osinfo/os/netbsd.org/netbsd-0.9.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.1.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.2.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.3.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.4.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.5.xml
/usr/share/osinfo/os/netbsd.org/netbsd-1.6.xml
/usr/share/osinfo/os/netbsd.org/netbsd-2.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-3.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-4.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-5.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-5.1.xml
/usr/share/osinfo/os/netbsd.org/netbsd-6.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-6.1.xml
/usr/share/osinfo/os/netbsd.org/netbsd-7.0.xml
/usr/share/osinfo/os/netbsd.org/netbsd-7.1.1.xml
/usr/share/osinfo/os/netbsd.org/netbsd-7.1.xml
/usr/share/osinfo/os/novell.com/netware-4.xml
/usr/share/osinfo/os/novell.com/netware-5.xml
/usr/share/osinfo/os/novell.com/netware-6.xml
/usr/share/osinfo/os/openbsd.org/openbsd-4.2.xml
/usr/share/osinfo/os/openbsd.org/openbsd-4.3.xml
/usr/share/osinfo/os/openbsd.org/openbsd-4.4.xml
/usr/share/osinfo/os/openbsd.org/openbsd-4.5.xml
/usr/share/osinfo/os/openbsd.org/openbsd-4.8.xml
/usr/share/osinfo/os/openbsd.org/openbsd-4.9.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.0.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.1.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.2.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.3.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.4.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.5.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.6.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.7.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.8.xml
/usr/share/osinfo/os/openbsd.org/openbsd-5.9.xml
/usr/share/osinfo/os/openbsd.org/openbsd-6.0.xml
/usr/share/osinfo/os/openbsd.org/openbsd-6.1.xml
/usr/share/osinfo/os/openbsd.org/openbsd-6.2.xml
/usr/share/osinfo/os/openbsd.org/openbsd-6.3.xml
/usr/share/osinfo/os/opensuse.org/opensuse-10.2.xml
/usr/share/osinfo/os/opensuse.org/opensuse-10.3.xml
/usr/share/osinfo/os/opensuse.org/opensuse-11.0.xml
/usr/share/osinfo/os/opensuse.org/opensuse-11.1.xml
/usr/share/osinfo/os/opensuse.org/opensuse-11.2.xml
/usr/share/osinfo/os/opensuse.org/opensuse-11.3.xml
/usr/share/osinfo/os/opensuse.org/opensuse-11.4.xml
/usr/share/osinfo/os/opensuse.org/opensuse-12.1.xml
/usr/share/osinfo/os/opensuse.org/opensuse-12.2.xml
/usr/share/osinfo/os/opensuse.org/opensuse-12.3.xml
/usr/share/osinfo/os/opensuse.org/opensuse-13.1.xml
/usr/share/osinfo/os/opensuse.org/opensuse-13.2.xml
/usr/share/osinfo/os/opensuse.org/opensuse-42.1.xml
/usr/share/osinfo/os/opensuse.org/opensuse-42.2.xml
/usr/share/osinfo/os/opensuse.org/opensuse-42.3.xml
/usr/share/osinfo/os/opensuse.org/opensuse-factory.xml
/usr/share/osinfo/os/opensuse.org/opensuse-tumbleweed.xml
/usr/share/osinfo/os/opensuse.org/opensuse-unknown.xml
/usr/share/osinfo/os/oracle.com/solaris-11.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.1.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.2.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.3.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.4.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.5.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.6.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.7.xml
/usr/share/osinfo/os/redhat.com/rhel-2.1.xml
/usr/share/osinfo/os/redhat.com/rhel-3.1.xml
/usr/share/osinfo/os/redhat.com/rhel-3.2.xml
/usr/share/osinfo/os/redhat.com/rhel-3.3.xml
/usr/share/osinfo/os/redhat.com/rhel-3.4.xml
/usr/share/osinfo/os/redhat.com/rhel-3.5.xml
/usr/share/osinfo/os/redhat.com/rhel-3.6.xml
/usr/share/osinfo/os/redhat.com/rhel-3.7.xml
/usr/share/osinfo/os/redhat.com/rhel-3.8.xml
/usr/share/osinfo/os/redhat.com/rhel-3.9.xml
/usr/share/osinfo/os/redhat.com/rhel-3.xml
/usr/share/osinfo/os/redhat.com/rhel-4.0.xml
/usr/share/osinfo/os/redhat.com/rhel-4.1.xml
/usr/share/osinfo/os/redhat.com/rhel-4.2.xml
/usr/share/osinfo/os/redhat.com/rhel-4.3.xml
/usr/share/osinfo/os/redhat.com/rhel-4.4.xml
/usr/share/osinfo/os/redhat.com/rhel-4.5.xml
/usr/share/osinfo/os/redhat.com/rhel-4.6.xml
/usr/share/osinfo/os/redhat.com/rhel-4.7.xml
/usr/share/osinfo/os/redhat.com/rhel-4.8.xml
/usr/share/osinfo/os/redhat.com/rhel-4.9.xml
/usr/share/osinfo/os/redhat.com/rhel-5.0.xml
/usr/share/osinfo/os/redhat.com/rhel-5.1.xml
/usr/share/osinfo/os/redhat.com/rhel-5.10.xml
/usr/share/osinfo/os/redhat.com/rhel-5.11.xml
/usr/share/osinfo/os/redhat.com/rhel-5.2.xml
/usr/share/osinfo/os/redhat.com/rhel-5.3.xml
/usr/share/osinfo/os/redhat.com/rhel-5.4.xml
/usr/share/osinfo/os/redhat.com/rhel-5.5.xml
/usr/share/osinfo/os/redhat.com/rhel-5.6.xml
/usr/share/osinfo/os/redhat.com/rhel-5.7.xml
/usr/share/osinfo/os/redhat.com/rhel-5.8.xml
/usr/share/osinfo/os/redhat.com/rhel-5.9.xml
/usr/share/osinfo/os/redhat.com/rhel-6.0.xml
/usr/share/osinfo/os/redhat.com/rhel-6.1.xml
/usr/share/osinfo/os/redhat.com/rhel-6.2.xml
/usr/share/osinfo/os/redhat.com/rhel-6.3.xml
/usr/share/osinfo/os/redhat.com/rhel-6.4.xml
/usr/share/osinfo/os/redhat.com/rhel-6.5.xml
/usr/share/osinfo/os/redhat.com/rhel-6.6.xml
/usr/share/osinfo/os/redhat.com/rhel-6.7.xml
/usr/share/osinfo/os/redhat.com/rhel-6.8.xml
/usr/share/osinfo/os/redhat.com/rhel-6.9.xml
/usr/share/osinfo/os/redhat.com/rhel-7.0.xml
/usr/share/osinfo/os/redhat.com/rhel-7.1.xml
/usr/share/osinfo/os/redhat.com/rhel-7.2.xml
/usr/share/osinfo/os/redhat.com/rhel-7.3.xml
/usr/share/osinfo/os/redhat.com/rhel-7.4.xml
/usr/share/osinfo/os/redhat.com/rhel-atomic-7.0.xml
/usr/share/osinfo/os/redhat.com/rhel-atomic-7.1.xml
/usr/share/osinfo/os/redhat.com/rhel-atomic-7.2.xml
/usr/share/osinfo/os/redhat.com/rhl-1.0.xml
/usr/share/osinfo/os/redhat.com/rhl-1.1.xml
/usr/share/osinfo/os/redhat.com/rhl-2.0.xml
/usr/share/osinfo/os/redhat.com/rhl-2.1.xml
/usr/share/osinfo/os/redhat.com/rhl-3.0.3.xml
/usr/share/osinfo/os/redhat.com/rhl-4.0.xml
/usr/share/osinfo/os/redhat.com/rhl-4.1.xml
/usr/share/osinfo/os/redhat.com/rhl-4.2.xml
/usr/share/osinfo/os/redhat.com/rhl-5.0.xml
/usr/share/osinfo/os/redhat.com/rhl-5.1.xml
/usr/share/osinfo/os/redhat.com/rhl-5.2.xml
/usr/share/osinfo/os/redhat.com/rhl-6.0.xml
/usr/share/osinfo/os/redhat.com/rhl-6.1.xml
/usr/share/osinfo/os/redhat.com/rhl-6.2.xml
/usr/share/osinfo/os/redhat.com/rhl-7.1.xml
/usr/share/osinfo/os/redhat.com/rhl-7.2.xml
/usr/share/osinfo/os/redhat.com/rhl-7.3.xml
/usr/share/osinfo/os/redhat.com/rhl-7.xml
/usr/share/osinfo/os/redhat.com/rhl-8.0.xml
/usr/share/osinfo/os/redhat.com/rhl-9.xml
/usr/share/osinfo/os/sun.com/opensolaris-2009.06.xml
/usr/share/osinfo/os/sun.com/solaris-10.xml
/usr/share/osinfo/os/sun.com/solaris-9.xml
/usr/share/osinfo/os/suse.com/sled-10.1.xml
/usr/share/osinfo/os/suse.com/sled-10.2.xml
/usr/share/osinfo/os/suse.com/sled-10.3.xml
/usr/share/osinfo/os/suse.com/sled-10.4.xml
/usr/share/osinfo/os/suse.com/sled-10.xml
/usr/share/osinfo/os/suse.com/sled-11.1.xml
/usr/share/osinfo/os/suse.com/sled-11.2.xml
/usr/share/osinfo/os/suse.com/sled-11.3.xml
/usr/share/osinfo/os/suse.com/sled-11.4.xml
/usr/share/osinfo/os/suse.com/sled-11.xml
/usr/share/osinfo/os/suse.com/sled-12.1.xml
/usr/share/osinfo/os/suse.com/sled-12.2.xml
/usr/share/osinfo/os/suse.com/sled-12.3.xml
/usr/share/osinfo/os/suse.com/sled-12.xml
/usr/share/osinfo/os/suse.com/sled-9.xml
/usr/share/osinfo/os/suse.com/sles-10.1.xml
/usr/share/osinfo/os/suse.com/sles-10.2.xml
/usr/share/osinfo/os/suse.com/sles-10.3.xml
/usr/share/osinfo/os/suse.com/sles-10.4.xml
/usr/share/osinfo/os/suse.com/sles-10.xml
/usr/share/osinfo/os/suse.com/sles-11.1.xml
/usr/share/osinfo/os/suse.com/sles-11.2.xml
/usr/share/osinfo/os/suse.com/sles-11.3.xml
/usr/share/osinfo/os/suse.com/sles-11.4.xml
/usr/share/osinfo/os/suse.com/sles-11.xml
/usr/share/osinfo/os/suse.com/sles-12.1.xml
/usr/share/osinfo/os/suse.com/sles-12.2.xml
/usr/share/osinfo/os/suse.com/sles-12.3.xml
/usr/share/osinfo/os/suse.com/sles-12.xml
/usr/share/osinfo/os/suse.com/sles-9.xml
/usr/share/osinfo/os/system76.com/popos-17.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-10.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-10.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-11.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-11.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-12.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-12.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-13.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-13.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-14.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-14.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-15.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-15.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-16.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-16.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-17.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-17.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-4.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-5.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-5.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-6.06.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-6.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-7.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-7.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-8.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-8.10.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-9.04.xml
/usr/share/osinfo/os/ubuntu.com/ubuntu-9.10.xml
/usr/share/osinfo/platform/linux-kvm.org/qemu-kvm-1.0.1.xml
/usr/share/osinfo/platform/linux-kvm.org/qemu-kvm-1.0.xml
/usr/share/osinfo/platform/linux-kvm.org/qemu-kvm-1.1.0.xml
/usr/share/osinfo/platform/linux-kvm.org/qemu-kvm-1.1.1.xml
/usr/share/osinfo/platform/linux-kvm.org/qemu-kvm-1.1.2.xml
/usr/share/osinfo/platform/linux-kvm.org/qemu-kvm-1.2.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.0.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.1.1-1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.1.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.1.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.2.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.2.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.2.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.3.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.3.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.4.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.4.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.4.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.5.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.5.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.5.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.5.3.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.6.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.6.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.6.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.7.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.7.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-1.7.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.0.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.0.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.0.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.1.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.1.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.1.2.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.1.3.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.2.0.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.2.1.xml
/usr/share/osinfo/platform/qemu.org/qemu-2.3.0.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.0.3.5.0.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.1.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.2.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.3.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.4.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.5.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.6.xml
/usr/share/osinfo/platform/redhat.com/xen-rhel-3.1.0.5.7.xml
/usr/share/osinfo/platform/xen.org/xen-3.0.2.xml
/usr/share/osinfo/platform/xen.org/xen-3.0.3.xml
/usr/share/osinfo/platform/xen.org/xen-3.0.4.xml
/usr/share/osinfo/platform/xen.org/xen-3.1.0.xml
/usr/share/osinfo/platform/xen.org/xen-3.1.3.xml
/usr/share/osinfo/platform/xen.org/xen-3.1.4.xml
/usr/share/osinfo/platform/xen.org/xen-3.2.0.xml
/usr/share/osinfo/platform/xen.org/xen-3.2.1.xml
/usr/share/osinfo/platform/xen.org/xen-3.2.2.xml
/usr/share/osinfo/platform/xen.org/xen-3.2.3.xml
/usr/share/osinfo/platform/xen.org/xen-3.3.0.xml
/usr/share/osinfo/platform/xen.org/xen-3.3.1.xml
/usr/share/osinfo/platform/xen.org/xen-3.3.2.xml
/usr/share/osinfo/platform/xen.org/xen-3.4.0.xml
/usr/share/osinfo/platform/xen.org/xen-3.4.1.xml
/usr/share/osinfo/platform/xen.org/xen-3.4.2.xml
/usr/share/osinfo/platform/xen.org/xen-3.4.3.xml
/usr/share/osinfo/platform/xen.org/xen-4.0.0.xml
/usr/share/osinfo/platform/xen.org/xen-4.0.1.xml
/usr/share/osinfo/platform/xen.org/xen-4.1.0.xml
/usr/share/osinfo/schema/osinfo.rng

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/osinfo-db-tools/COPYING
/usr/share/package-licenses/osinfo-db-tools/osinfo-db_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/osinfo-db-export.1
/usr/share/man/man1/osinfo-db-import.1
/usr/share/man/man1/osinfo-db-path.1
/usr/share/man/man1/osinfo-db-validate.1

%files locales -f osinfo-db-tools.lang
%defattr(-,root,root,-)

