#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0x97D9123DE37A484F (toso@posteo.net)
#
Name     : osinfo-db-tools
Version  : 1.11.0
Release  : 19
URL      : https://releases.pagure.org/libosinfo/osinfo-db-tools-1.11.0.tar.xz
Source0  : https://releases.pagure.org/libosinfo/osinfo-db-tools-1.11.0.tar.xz
Source1  : https://releases.pagure.org/libosinfo/osinfo-db-tools-1.11.0.tar.xz.asc
Summary  : Tools for managing the osinfo database
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: osinfo-db-tools-bin = %{version}-%{release}
Requires: osinfo-db-tools-license = %{version}-%{release}
Requires: osinfo-db-tools-locales = %{version}-%{release}
Requires: osinfo-db-tools-man = %{version}-%{release}
Requires: osinfo-db-data
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : json-glib-dev
BuildRequires : libarchive-dev
BuildRequires : libsoup-dev
BuildRequires : osinfo-db-data
BuildRequires : perl(Getopt::Long)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsoup-3.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This package provides tools for managing the osinfo database of
information about operating systems for use with virtualization

%package bin
Summary: bin components for the osinfo-db-tools package.
Group: Binaries
Requires: osinfo-db-tools-license = %{version}-%{release}

%description bin
bin components for the osinfo-db-tools package.


%package license
Summary: license components for the osinfo-db-tools package.
Group: Default

%description license
license components for the osinfo-db-tools package.


%package locales
Summary: locales components for the osinfo-db-tools package.
Group: Default

%description locales
locales components for the osinfo-db-tools package.


%package man
Summary: man components for the osinfo-db-tools package.
Group: Default

%description man
man components for the osinfo-db-tools package.


%prep
%setup -q -n osinfo-db-tools-1.11.0
cd %{_builddir}/osinfo-db-tools-1.11.0
pushd ..
cp -a osinfo-db-tools-1.11.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702042842
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/osinfo-db-tools
cp %{_builddir}/osinfo-db-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/osinfo-db-tools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang osinfo-db-tools
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/osinfo-db-export
/V3/usr/bin/osinfo-db-import
/V3/usr/bin/osinfo-db-path
/V3/usr/bin/osinfo-db-validate
/usr/bin/osinfo-db-export
/usr/bin/osinfo-db-import
/usr/bin/osinfo-db-path
/usr/bin/osinfo-db-validate

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/osinfo-db-tools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/osinfo-db-export.1
/usr/share/man/man1/osinfo-db-import.1
/usr/share/man/man1/osinfo-db-path.1
/usr/share/man/man1/osinfo-db-validate.1

%files locales -f osinfo-db-tools.lang
%defattr(-,root,root,-)

